version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    

    
