"""003 add is_active property to property

Revision ID: 2bab66cacf54
Revises: 0fa6af3dfbf9
Create Date: 2024-05-26 12:37:34.370321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bab66cacf54'
down_revision: Union[str, None] = '0fa6af3dfbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'is_active')
    # ### end Alembic commands ###
